name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Build with dotnet
      run: bash build.sh
      shell: bash
      working-directory: ./build
    - name: Publish NuGet packages to github
      run: |
           for nugetPackage in ./LocalNuGetRepo/*.nupkg
           do
             curl -vX PUT -u "tix-factory:${{ secrets.github_token }}" -F package=@$nugetPackage https://nuget.pkg.github.com/tix-factory/
           done
      shell: bash
    - name: Publish NuGet packages to nuget.org
      run: dotnet nuget push ./LocalNuGetRepo/**/*.nupkg --api-key ${{ secrets.nuget_apikey }} --source https://api.nuget.org/v3/index.json --no-symbols true
