name: .NET Core

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Generate msbuild project file
      uses: tix-factory/msbuild-project-generator@v1.0.1
      with:
        directory: ./
        projectFile: ./build/build.proj
    - name: Build with dotnet
      run: sh build.sh
      shell: bash
      working-directory: ./build
    - name: Publish artifacts
      run: sh publish.sh
      shell: bash
      working-directory: ./build
    - name: Create Release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: tix-factory/release-manager@v1
      with:
        github_token: ${{ secrets.github_token }}
        mode: uploadReleaseAsset
        filePath: ./build/publish.zip
        assetName: publish.zip
        tag: ${{ format('release-number-{0}', env.BUILD_NUMBER) }}
    - name: Attach NuGet packages to release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: tix-factory/release-manager@v1
      with:
        github_token: ${{ secrets.github_token }}
        mode: uploadReleaseAsset
        filePath: ./build/nuget.zip
        assetName: nuget.zip
        tag: ${{ format('release-number-{0}', env.BUILD_NUMBER) }}
    - name: Publish NuGet packages
      if: ${{ github.ref == 'refs/heads/master' }}
      run: sh nuget_publish.sh ${{ secrets.github_token }} ${{ secrets.nuget_apikey }}
      shell: bash
      working-directory: ./build
