name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Build with dotnet
      run: bash build.sh
      shell: bash
      working-directory: ./build
    - name: Setup nuget.config for github
      run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
      working-directory: ./build
    - name: Publish NuGet packages to github
      run: dotnet nuget push ./../LocalNuGetRepo/**/*.nupkg --source "GPR"
      working-directory: ./build
    - name: Publish NuGet packages to nuget.org
      run: dotnet nuget push ./LocalNuGetRepo/**/*.nupkg --api-key ${{ secrets.nuget_apikey }} --source https://api.nuget.org/v3/index.json --no-symbols true
